### PR TITLE
Fix tuple arguments for :cancel cast. Closes #35

### LINKED ISSUE #35: (Owner.handle_cast/2) FunctionClauseError
DB Connection version: 0.2.5

Opening this issue to better track it.

Using manual checkout mode.  Haven't been able to track down exactly how or when this happens yet.

```
11:35:19.122 [error] Postgrex.Protocol (#PID<0.1074.0>) disconnected: ** (DBConnection.Error) client down
11:35:19.142 [error] GenServer #PID<0.1101.0> terminating
** (FunctionClauseError) no function clause matching in anonymous fn/1 in DBConnection.Ownership.Owner.handle_cast/2
    (db_connection) lib/db_connection/ownership/owner.ex:170: anonymous fn({{#Reference<0.0.2.4968>, #Reference<0.0.2.4970>}, 15000, {#PID<0.1100.0>, #Reference<0.0.2.4969>}}) in DBConnection.Ownership.Owner.handle_cast/2
    (stdlib) queue.erl:369: :queue.filter_f/2
    (stdlib) queue.erl:353: :queue.filter/2
    (db_connection) lib/db_connection/ownership/owner.ex:178: DBConnection.Ownership.Owner.handle_cast/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
11:35:19.142 [error] #PID<0.1098.0> running SchedWeb.Endpoint terminated
Server: localhost:4001 (http)
Request: POST /login
** (exit) exited in: GenServer.call(#PID<0.1101.0>, {:checkout, #Reference<0.0.5.2433>, true, 15000}, 5000)
    ** (EXIT) time out
11:35:19.143 [error] Process #PID<0.1100.0> raised an exception
** (Postgrex.Error) tcp recv: closed
    (ecto) lib/ecto/adapters/sql.ex:405: Ecto.Adapters.SQL.struct/6
    (ecto) lib/ecto/repo/schema.ex:373: Ecto.Repo.Schema.apply/5
    (ecto) lib/ecto/repo/schema.ex:179: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
    (ecto) lib/ecto/repo/schema.ex:584: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
    (ecto) lib/ecto/adapters/sql.ex:450: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1079: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1009: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:766: DBConnection.transaction/3
```

Appears to be a bug in DBConnection.

### PR DESCRIPTION
**Pull request by stavro**

### CODE REVIEW

**Comment by fishcakez** [comment]
The fix is perfect but could we get a test please?

**Comment by stavro** [comment]
@fishcakez I dug in a bit to try and build a test, but I don't fully understand what's going on enough with the owner / ownership / pool exiting status during a checkout.

I can try to spend more time on it later, but I haven't been able to put together any meaningful test yet.

**Comment by fishcakez** [comment]
We need to create some tests where the check out times out. The easiest would be with nested runs:
```elixir
DBConnection.run(pid, fn(_) ->
  DBConnection.run(pid, fn(_) -> flunk("did not time out") end)
end)
```
Unfortunately time outs cause different errors depending on the pool. We would need to use tags and have one test for the sojourn pool with assert_raise and one test for the other pools with `assert {:timeout, _} = catch_exit ..`

I guess the best spot for this would be queue_test.exs.

**Comment by fishcakez** [comment]
Thank you! :heart:

I have added a test in https://github.com/fishcakez/db_connection/commit/1d764119530e350a30d82e0299a547ea7e0d56d9

**Comment by alakra** [comment]
When can we expect this to get into a tagged release?

**Comment by fishcakez** [comment]
@alakra I will aim to tag v1.0 earlier next week. If this is causing you issues I can create a 0.2 branch and cherrypick this/release new 0.2.* release.

**Comment by alakra** [comment]
I can wait for 1.0. Thanks for such a quick response!

On Fri, May 27, 2016 at 1:53 PM James Fish <notifications@github.com> wrote:

> @alakra <https://github.com/alakra> I will aim to tag v1.0 earlier next
> week. If this is causing you issues I can create a 0.2 branch and
> cherrypick this/release new 0.2.* release.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fishcakez/db_connection/pull/36#issuecomment-222238663>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAK95HuwHT9ubBaZiHnNqMWuX7SKASFks5qF0ufgaJpZM4IRXpR>
> .
>
-- 
    - Angelo Lakra

**Pull request merged**
